#!/usr/bin/env python3
"""Authoring helper for faces/non-circular-gears/watchface.xml.

    python3 faces/non-circular-gears/generate_assets.py
    python3 faces/non-circular-gears/generate_xml.py

The XML it writes is the face; this script never runs on the watch.
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
import geometry as g  # noqa: E402
from generate_assets import GEAR_HALF, hand_box  # noqa: E402

OUT = HERE / "watchface.xml"

RED = "#E2553B"
INK = "#141416"
RUBY = "#B0243A"

# Uniform driver angles. The seconds pair turns once a minute; the minute hand
# follows the same law once an hour.
U_SEC = "([SECOND] + [MILLISECOND] / 1000) * 6"
U_MIN = "([MINUTE] + [SECOND] / 60) * 6"
HOUR = "(([HOUR_0_23] % 12) * 30 + [MINUTE] * 0.5 + [SECOND] / 120)"

SECOND_HAND = g.follower_expr(U_SEC)
MINUTE_HAND = g.follower_expr(U_MIN)
FOLLOWER_BODY = f"{SECOND_HAND} + 180"
DRIVER_BODY = f"180 - {U_SEC}"


def f(v: float) -> str:
    return f"{v:.2f}".rstrip("0").rstrip(".")


def gear(name: str, centre: tuple[float, float], angle: str) -> str:
    cx, cy = centre
    s = GEAR_HALF
    return (f'      <Group x="{f(cx - s)}" y="{f(cy - s)}" width="{f(2 * s)}" height="{f(2 * s)}" '
            f'name="{name}" pivotX="0.5" pivotY="0.5">\n'
            f'        <Transform target="angle" value="{angle}" />\n'
            f'        <PartImage x="0" y="0" width="{f(2 * s)}" height="{f(2 * s)}">\n'
            f'          <Image resource="gear" />\n'
            f'        </PartImage>\n'
            f'      </Group>')


def image_hand(name: str, angle: str, ambient_alpha: int | None = None) -> str:
    w, h, pivot = hand_box(name)
    x, y = 225 - w / 2, 225 - pivot
    variant = (f'      <Variant mode="AMBIENT" target="alpha" value="{ambient_alpha}" />\n'
               if ambient_alpha is not None else "")
    return (f'    <Group x="{f(x)}" y="{f(y)}" width="{f(w)}" height="{f(h)}" name="{name}Hand" '
            f'pivotX="0.5" pivotY="{pivot / h:.5f}">\n'
            f'{variant}'
            f'      <Transform target="angle" value="{angle}" />\n'
            f'      <PartImage x="0" y="0" width="{f(w)}" height="{f(h)}">\n'
            f'        <Image resource="{name}" />\n'
            f'      </PartImage>\n'
            f'    </Group>')


def second_hand() -> str:
    # Rides the follower's arbor: the same angle as the follower gear, less the
    # 180 degrees that put the gear's long side along the hand.
    tip, tail = 210, 44
    return (f'    <Group x="0" y="0" width="450" height="450" name="secondHand" pivotX="0.5" pivotY="0.5">\n'
            f'      <Variant mode="AMBIENT" target="alpha" value="0" />\n'
            f'      <Transform target="angle" value="{SECOND_HAND}" />\n'
            f'      <PartDraw x="0" y="0" width="450" height="450">\n'
            f'        <Line startX="225" startY="{225 + tail}" endX="225" endY="{225 - tip}">\n'
            f'          <Stroke color="{RED}" thickness="1.8" cap="ROUND" />\n'
            f'        </Line>\n'
            # Counterweight: a small ellipse, the gear's own profile in miniature.
            f'        <Ellipse x="219.5" y="{225 + tail - 22}" width="11" height="16">\n'
            f'          <Fill color="{RED}" />\n'
            f'        </Ellipse>\n'
            f'        <Ellipse x="219" y="219" width="12" height="12">\n'
            f'          <Fill color="{RED}" />\n'
            f'        </Ellipse>\n'
            f'        <Ellipse x="222.5" y="222.5" width="5" height="5">\n'
            f'          <Fill color="{INK}" />\n'
            f'        </Ellipse>\n'
            f'      </PartDraw>\n'
            f'    </Group>')


def driver_jewel() -> str:
    cx, cy = g.DRIVER
    return (f'      <PartDraw x="0" y="0" width="450" height="450">\n'
            f'        <Ellipse x="{f(cx - 7)}" y="{f(cy - 7)}" width="14" height="14">\n'
            f'          <Fill color="#8C929A" />\n'
            f'        </Ellipse>\n'
            f'        <Ellipse x="{f(cx - 4.6)}" y="{f(cy - 4.6)}" width="9.2" height="9.2">\n'
            f'          <Fill color="{RUBY}" />\n'
            f'        </Ellipse>\n'
            f'        <Ellipse x="{f(cx - 2.6)}" y="{f(cy - 3.2)}" width="2.6" height="2.6">\n'
            f'          <Fill color="#F4A7B2" />\n'
            f'        </Ellipse>\n'
            f'      </PartDraw>')


def build() -> str:
    parts = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by faces/non-circular-gears/generate_xml.py. Edit the generator, then regenerate. -->',
        '<WatchFace width="450" height="450" clipShape="CIRCLE">',
        '  <Metadata key="CLOCK_TYPE" value="ANALOG" />',
        '  <Metadata key="PREVIEW_TIME" value="10:08:36" />',
        '  <Scene backgroundColor="#000000">',
        '    <!-- Movement: the gears behind the dial window (hidden in ambient) -->',
        '    <Group x="0" y="0" width="450" height="450" name="movement">',
        '      <Variant mode="AMBIENT" target="alpha" value="0" />',
        '      <PartImage x="0" y="0" width="450" height="450">',
        '        <Image resource="movement" />',
        '      </PartImage>',
        '      <!-- Driver: turns uniformly, once a minute, counter-clockwise -->',
        gear("driverGear", g.DRIVER, DRIVER_BODY),
        driver_jewel(),
        '      <!-- Follower: on the hand arbor; long side along the second hand -->',
        gear("followerGear", g.CENTER, FOLLOWER_BODY),
        '      <!-- Dial plate with the window cut out, the scale and hour batons -->',
        '      <PartImage x="0" y="0" width="450" height="450">',
        '        <Image resource="dial" />',
        '      </PartImage>',
        '    </Group>',
        '    <!-- Ambient dial: scale and numerals only -->',
        '    <Group x="0" y="0" width="450" height="450" name="ambientDial" alpha="0">',
        '      <Variant mode="AMBIENT" target="alpha" value="255" />',
        '      <PartImage x="0" y="0" width="450" height="450">',
        '        <Image resource="ambient" />',
        '      </PartImage>',
        '    </Group>',
        '    <!-- Hour: uniform, against the batons -->',
        image_hand("hour", HOUR, ambient_alpha=200),
        '    <!-- Minute: the follower law over the hour, against the stretched scale -->',
        image_hand("minute", MINUTE_HAND, ambient_alpha=220),
        '    <!-- Second: fixed to the follower gear -->',
        second_hand(),
        '  </Scene>',
        '</WatchFace>',
    ]
    return "\n".join(parts) + "\n"


if __name__ == "__main__":
    OUT.write_text(build())
    print(f"wrote {OUT}")
